# Site
name: "Patrik Pekarčík"
title: "Patrik Pekarčík - Ústav Informatiky UPJŠ"
description: "Osobná webstránka určená pre zdielanie informácií so študentami."
meta_description: "Osobná webstránka určená pre zdielanie informácií so študentami"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/'
email: 'patrik.pekarcik@student.upjs.sk'
google_analytics: 'UA-60611019-13'
disqus: 'ppatrik'
post_dirs: true
#sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  ppatrik:
    name: Patrik Pekarčík
    display_name: Patrik Pekarčík
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: patrik.pekarcik@student.upjs.sk
    web: https://ppatrik.github.io
    twitter: https://twitter.com/patrik_fm
    description: "Phd. student at University of Pavol Jozef Safarik in Kosice"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge
